### PR TITLE
Edit/phonenumber

### PR DESCRIPTION
**Pull request by matrharr**

### CODE REVIEW

**Comment by jszwedko** [comment]
Looks good 👍

**Comment by grepdisc** [comment]
@jszwedko: Here is a process question. This Pull Request has been closed, merged, and the code has been pushed to staging for testing. This bug-fix will now be modified according to https://www.pivotaltracker.com/story/show/134200243 before deploying to Production. What is a good process? Re-open this Pull Request and re-merge? Make the changes in another Pull Request, and merge that one without regard to this one?

**Comment by jszwedko** [comment]
@grepdisc Aha, I see! I would say another pull request -- I merged this primarily to get it up onto the staging environment for testing.

**Comment by grepdisc** [comment]
Thank you. Using a new pull request sounds great. I appreciate your direction.

**Pull request merged**
