### PR TITLE
new/searchreports

### PR DESCRIPTION
**Pull request by matrharr**

### CODE REVIEW

**Comment by grepdisc** [comment]
It looks like the file Gemfile.lock needs to be updated and checked into version control in order for Travis CI to successfully test the code.

**Comment by jszwedko** [comment]
Indeed, I think just a `bundle install` along with checking in the updated `Gemflie.lock` should do it.

**Comment by matrharr** [comment]
got it, I will add the file and make another pull request

**Comment by grepdisc** [comment]
I see that the most recent push failed due to being unable to install the gem "listen" version 3.1.5
Looking at gemfile.lock, I see a bunch of changes. I would imagine that it makes sense to include updates in this PR only to the gems that are required by pg_search, but I don't know how to do that.
One interesting piece is that I notice that [line 375](https://github.com/egavas629/concrn-rails/pull/58/files#diff-e79a60dcL375) has been removed, and I wonder if not requiring a specific version of ruby caused the other gems to be updated. I should note that I think 2.0.0p648 is the version of ruby we are using, despite a different version being listed in the file [.ruby_version](https://github.com/egavas629/concrn-rails/blob/134f513/.ruby-version)

**Pull request merged**
