### PR TITLE
Gracefully handle google places error

### PR DESCRIPTION
**Pull request by matrharr**
When the google places api key is invalid, this fix will handle the error without crashing the app.

### CODE REVIEW

**Comment by jszwedko** [comment]
:+1: I'm guessing the end result of this is an error message in the field for the neighborhood saying something like "Missing Google API key"?

**Comment by matrharr** [comment]
Yes! If the begin block throws an error(the api key missing) the rescue block catches it. There is already handling on the front end in reports/show.html.haml. This fix is to prevent an app crashing error.

**Comment by jszwedko** [comment]
:+1:

**Comment by jszwedko** [comment]
Would you mind adding a test asserting that the exception is caught? You should be able to stub out the `clients.spots` method to raise.

**Comment by jszwedko** [comment]
Possible testing approach: https://github.com/matrharr/concrn-rails/pull/9

**Pull request merged**
