### PR TITLE
disable similar reports in view

### PR DESCRIPTION
**Pull request by matrharr**

### CODE REVIEW

**Comment by jszwedko** [comment]
@matrharr can you add a comment about why this section is commented out?

**Comment by matrharr** [comment]
While "similar reports" could become a useful feature, it is disabled because it currently serves as a non-functional distraction to dispatchers.

**Comment by grepdisc** [comment]
@jszwedko: Are you asking for a comment here or a comment directly in the code?

Here is some updated text for a comment:
While "similar reports" could become a useful feature, it is disabled because it currently serves as a non-functional distraction to dispatchers.

**Comment by jszwedko** [comment]
Apologies, I meant a comment in the code 😄  Would help future spelunkers understand why that segment is commented. Alternatively, unless you plan to reinstate it in the near future. I'd argue for just deleting it and writing why in the commit message.

**Comment by grepdisc** [comment]
Replaced by #64

**Pull request closed without merging**
